/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#0058bc",
        "primary-container": "#0070eb",
        "primary-fixed": "#d8e2ff",
        "primary-fixed-dim": "#adc6ff",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefcff",
        "secondary": "#785900",
        "secondary-container": "#fdc003",
        "secondary-fixed": "#ffdf9e",
        "secondary-fixed-dim": "#fabd00",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#6c5000",
        "tertiary": "#a83206",
        "tertiary-container": "#ca4a20",
        "tertiary-fixed": "#ffdbd0",
        "tertiary-fixed-dim": "#ffb59f",
        "on-tertiary": "#ffffff",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "surface": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "surface-container-highest": "#e1e3e4",
        "on-surface": "#191c1d",
        "on-surface-variant": "#414755",
        "outline": "#717786",
        "outline-variant": "#c1c6d7",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["'Plus Jakarta Sans'", "sans-serif"],
        label: ["'Inter'", "sans-serif"],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
      }
    },
  },
  plugins: [],
}
